from approach_person import ApproachPersonPointing
from pointing_location_detection import PointingLocationDetection
from object_detection import ObjectDetection
from approach_pointed_object import ApproachPointedObject
from pointed_object_detection import PointedObjectDetection
from look_at_person_gesturing import LookAtPersonGesturing
from object_disambiguation import ObjectDisambiguation

#from start import Start
#from manipulate import Manipulate
#from deposit import Deposit
