# 2d image and point cloud messages as input data to pointing 
sensor_msgs/Image img_msg
sensor_msgs/PointCloud2 depth_points
---
# Output data from the openpose server
string hand
float32[] hand_tip
float32[] head
sensor_msgs/Image open_pose_output_image_msg