apple:
  colour: 
    ["red"]
  type:
    ["fresh"]
  texture:
    ["smooth"]
  size:
    ["small", "medium"]
  shape:
    ["round", "circle", "sphere"]

banana:
  colour: 
    ["yellow"]
  type:
    ["fresh"]
  texture:
    ["smooth"]
  size:
    ["medium", "large", "long"]
  shape:
    ["curved"]
