object_attributes:
  - name: 'apple'
    colour: 'red'
    type: 'fresh'
    texture: 'smooth'
    size: 'medium'
    shape: 'round'

  - name: 'banana'
    colour: 'yellow'
    type: 'fresh'
    texture: 'smooth'
    size: 'long'
    shape: 'curved'

  - name: 'orange'
    colour: 'orange'
    type: 'fresh'
    texture: 'wrinkled'
    size: 'medium'
    shape: 'round'

  - name: 'bowl'
    colour: 'white'
    type: 'vessel'
    texture: 'smooth'
    size: 'large'
    shape: 'round'

list_of_attributes:
  - colour: ['red','orange','yellow']
    type: ['fresh']
    texture: ['smooth','wrinkled']
    size: ['medium','long', 'large']
    shape: ['round', 'curved']
    position: ["north", "right", "east", "down", "south", "left", "west", "up", "north", "centre"]

list_of_objects_capable_of_disambiguation: ['apple', 'banana', 'orange']
