object_attributes:
  - name: 'apple'
    colour: ['red','green']
    smooth: 'yes'
    shape: ['round', 'conical', 'flat round', 'flat', 'long conical', 'round conical', 'round oblong', 'square oblong']

  - name: 'banana'
    colour: ['yellow','green']
    smooth: 'yes'
    shape: ['curved','long','curvey','thick','thin', 'fat']

  - name: 'orange'
    colour: ['orange','green']
    smooth: 'no'
    shape: ['round','sphere','oval']



list_of_attributes:
  - colour: ['red','orange','yellow','green']
    smooth: ['yes','no']
    shape: ['round', 'conical', 'flat round', 'flat', 'long conical', 'round conical', 'round oblong', 'square oblong','curved','long','curvey','thick','thin', 'fat','sphere','oval']
    position: ["north", "front", "right", "east", "behind", "south", "left", "west", "centre"]

list_of_objects_capable_of_disambiguation: ['apple', 'banana', 'orange']
