object_attributes:
  - name: 'apple'
    colour: 'red'
    type: 'fresh'
    texture: 'smooth'
    size: 'medium'
    shape: 'round'

  - name: 'banana'
    colour: 'yellow'
    type: 'fresh'
    texture: 'smooth'
    size: 'long'
    shape: 'curved'

  - name: 'orange'
    colour: 'orange'
    type: 'fresh'
    texture: 'wrinkled'
    size: 'medium'
    shape: 'round'

  - name: 'bowl'
    colour: 'white'
    type: 'vessel'
    texture: 'smooth'
    size: 'large'
    shape: 'round'

# object_attributes:
#   object0:
#     name:
#       ["apple"]
#     colour: 
#       ["red"]
#     type:
#       ["fresh"]
#     texture:
#       ["smooth"]
#     size:
#       ["small", "medium"]
#     shape:
#       ["round", "circle", "sphere"]

#   object1:
#     name:
#       ["banana"]
#     colour: 
#       ["yellow"]
#     type:
#       ["fresh"]
#     texture:
#       ["smooth"]
#     size:
#       ["medium", "large", "long"]
#     shape:
#       ["curved"]

#   object2:
#     name:
#       ["orange"]
#     colour: 
#       ["orange"]
#     type:
#       ["fresh"]
#     texture:
#       ["wrinkled"]
#     size:
#       ["small", "medium"]
#     shape:
#       ["round", "circle", "sphere"]