fruits:
  - name: '013_apple_textured_100'
    pose: { x: 3.347980, y: -5.22571, z: 1.015310, roll: 0.001553, pitch: -0.003983, yaw: -0.262727 }
    link: {name: '013_apple_textured'}

  - name: '011_banana_textured_300'
    pose: { x: 3.1, y: -5.493759, z: 1.015395, roll: -0.007460, pitch: -0.007460, yaw: 0.013401 }
    link: {name: '011_banana_textured'}

guests:
  - name: 'person_standing'
    pose:  { x: 2.39, y: -1.74, z: 0.0, roll: 0, pitch: 0, yaw: 0  }

  - name: 'girl_pointing'
    pose:  { x: -0.26, y: -6.39, z: 0.0, roll: 0, pitch: 0, yaw: -0.93  }
