play_motion:
  motions:
    lift_torso:
      joints: ['torso_lift_joint']
      points:
      - positions: [0.34]
        time_from_start: 2.5

    lower_torso:
      joints: ['torso_lift_joint']
      points:
      - positions: [0.08]
        time_from_start: 2.5

    lift_head:
      joints: ['head_1_joint', 'head_2_joint']
      points:
      - positions: [0.0, 0.0]
        time_from_start: 2.0

    lower_head:
      joints: ['head_1_joint', 'head_2_joint']
      points:
      - positions: [0.0, -0.75]
        time_from_start: 2.0

    back_to_default:
      joints: ['torso_lift_joint', 'head_1_joint', 'head_2_joint']
      points:
      - positions: [0.34, 0.0, -0.15]
        time_from_start: 0.0

